### ISSUE TITLE
(feat.): StreamAlert

### ISSUE THREAD

**Issue by pauliesnug** [Inrixia/floatplaneAPI.ts#2]
Maybe an endpoint that works as an Event that tells when there a stream is started?

**Comment by Inrixia** [comment]
If there was an event for it it would be under https://github.com/Inrixia/floatplaneAPI.ts/commit/23e156b0519d9b947fcafaf8118901fc7f55a161

However as far as I am aware the sails endpoint no longer receives events due to some issue on floatplanes side.
That said I have not ran an event listener for a few days to verify this, at some point I might test this using the old version of the library that supports sails. Or you can.

However even if sails support works unless there is support for desktop notifications on floatplane for live streams starting (which looking at it now it doesn't appear there is) then there is no way to get an event for it.

The next best thing would be to poll for a livestream blogpost, this is something I have been considering for https://github.com/Inrixia/Floatplane-Downloader/issues/98

Let me know your thoughts

**Comment by pauliesnug** [comment]
Thanks :D
